compounds: 2000
models:
  - allenai/OLMo-2-0425-1B-Instruct
  - amd/Instella-3B-Instruct
  - arcee-ai/AFM-4.5B
  - google/gemma-3n-E2B-it
  - HuggingFaceTB/SmolLM3-3B
  - ibm-granite/granite-3.3-2b-instruct
  - MegaScience/Qwen3-1.7B-MegaScience
  - meta-llama/Llama-3.2-3B-Instruct
  - microsoft/MediPhi
  - microsoft/Phi-3.5-mini-instruct
  - Qwen/Qwen3-4B-Instruct-2507
  - utter-project/EuroLLM-1.7B-Instruct
  # - deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
  # - janhq/Jan-v1-4B
  # - nvidia/Nemotron-Research-Reasoning-Qwen-1.5B
  # - apple/OpenELM-3B-Instruct
  # - openai/gpt-oss-20b
  # - mistralai/Mistral-7B-Instruct-v0.2
  # - microsoft/Phi-4-mini-instruct
  # - bigscience/bloomz-3b
  # - tencent/Hunyuan-4B-Instruct
pubchem_xml_file: pubmed_compounds/Compound_000000001_000500000.xml
t3db_xml_file: t3db/toxins.xml
data_file: full_compounds.csv
results_file: full_results.csv
report_file: full_report.txt
plots_file: full_plots.pdf
max_smiles_length: 250
min_smiles_length: 50
