compounds: 500
models:
  - allenai/OLMo-2-0425-1B-Instruct
  - CohereLabs/aya-expanse-8b
pubchem_xml_file: pubmed_compounds/Compound_000000001_000500000.xml
t3db_xml_file: t3db/toxins.xml
data_file: small_compounds.csv
results_file: small_results.csv
report_file: small_report.txt
plots_file: small_plots.pdf
max_smiles_length: 75
min_smiles_length: 25
